version: '2'

services:
  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=varo
      - POSTGRES_PASSWORD=varo
      - POSTGRES_DB=backend-test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
  app:
    image: 'app:latest'
    build:
      context: .
    ports:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend-test
      - SPRING_DATASOURCE_USERNAME=varo
      - SPRING_DATASOURCE_PASSWORD=varo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
  nginx:
    image: 'nginx:latest'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "4000:4000"

networks:
  default:
    driver: bridge
    name: app